apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart3
  template:
    metadata:
      labels:
        app: cart3
    spec:
      containers:
      - name: cart3
        image: gcr.io/oceanic-craft-302516/cart3:latest
        ports:
        - containerPort: 8092
        imagePullPolicy: Always